---
title: "How me and my partner use Netflix"
output: 
  flexdashboard::flex_dashboard:
    theme: readable
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(chron)
library(extrafont)
library(dplyr)
library(shiny)
```

```{r}
PATH <- #ASSIGN YOUR PATH HERE
  
```


```{r}
#loading data
data <- read.csv(PATH)

#transforming times and dates into appropriate formats
data$Duration <- as.times(data$Duration)
data$Start.Time <- as.Date(data$Start.Time)
data$dur_in_min <- round(hours(data$Duration)*60+minutes(data$Duration) + 
                           seconds(data$Duration)/60, 1)
#loading fonts
loadfonts(device = "win", quiet = TRUE)

#filtering the titles
data$general_title=NULL
for (i in 1:length(data$Title)) {
  ind = regexpr("Seizoen",data$Title[i])
  if (ind<0) {
    ind=regexpr("Season",data$Title[i])
  }
  if (ind<0) {
    ind=regexpr("Miniserie",data$Title[i])
  }
  if (ind>0){
    sub=substr(data$Title[i],1,ind-3)
    data$general_title[i]=sub
  } else {
    data$general_title[i]=data$Title[i]
  }
}
#aggregating data according to the titles
aggr_by_title = data %>%
  group_by(general_title) %>% 
  summarise(total_dur_in_min = sum(dur_in_min))
aggr_by_title = aggr_by_title[order(-aggr_by_title$total_dur_in_min),]
#running the model that produces the abline
mod2 <- lm(dur_in_min~Start.Time,data)
coefs <- mod2$coefficients

#aggregating data per years
data$years <- years(data$Start.Time)
aggr_by_year = data %>%
  group_by(years) %>% 
  summarise(total_dur_in_min = sum(dur_in_min))
aggr_by_year$years_as_f <- as.factor(aggr_by_year$years)
```


Column {data-width=600}
-----------------------------------------------------------------------

###
```{r}
par(mar=c(10,4,4,1.5))
bp = barplot(aggr_by_title$total_dur_in_min[1:10]/60,
             names.arg=aggr_by_title$general_title[1:10],  
     xlab="",
     ylab="total hrs",
     ylim = c(0,155),
     yaxt="n",
     col="deepskyblue3", border = "deepskyblue3",
     las=2,
     main="What we were watching",
     fg="gray30",
     cex.main=1.8,col.main="gray30",
     cex.lab = 1.4, col.lab = "gray40", font.lab=2, 
     cex.axis = 1.2, col.axis = "gray30",
     family="Century Gothic")
text(bp, aggr_by_title$total_dur_in_min[1:10]/60+12,
     labels=as.character(round(aggr_by_title$total_dur_in_min[1:10]/60,1)),
     col = "gray30",
     family = "Century Gothic")
```

Column {data-width=400}
-----------------------------------------------------------------------

###

```{r}

plot(data$Start.Time, data$dur_in_min, 
     xlab="year",ylab="min per view",
     pch=16, col="deepskyblue3",
     bty="l",fg="gray30",
     main="For how long we watched it",
     cex.main=1.8,col.main="gray30",
     cex.lab = 1.4, col.lab = "gray40", font.lab=2, 
     cex.axis = 1.2, col.axis = "gray30",
     family="Century Gothic")
abline(coefs[1],coefs[2],col="sienna1",lwd=3)
```

### 

```{r}
barplot(aggr_by_year$total_dur_in_min/60,
         names.arg=aggr_by_year$years_as_f,  
         xlab="year",
         ylab="hours watched",
         col="deepskyblue3", border = "deepskyblue3",
         main="How much we watched per year",
         fg="gray30",
         cex.main=1.8,col.main="gray30",
         cex.lab = 1.4, col.lab = "gray40", font.lab=2, 
         cex.axis = 1.2, col.axis = "gray30",
         family="Century Gothic")
```

<style type="text/css">
 .navbar-header{ 
  font-family: Century Gothic;
}
</style>

<style type="text/css">
 .chart-shim{ 
  font-family: Century Gothic;
}
</style>
